# Generated by Django 3.0.8 on 2020-07-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosGenerales',
            fields=[
                ('id_datos_generales', models.IntegerField(primary_key=True, serialize=False)),
                ('anyo', models.IntegerField()),
                ('epoca', models.IntegerField(choices=[(0, 'seca'), (1, 'humeda')])),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('nombre', models.CharField(max_length=50)),
                ('punto_muestreo', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('comunidad', models.CharField(max_length=50)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('zona_utm', models.CharField(max_length=10)),
                ('altura', models.FloatField()),
            ],
            options={
                'verbose_name': 'dato general',
                'verbose_name_plural': 'Datos Generales',
                'ordering': ('anyo',),
            },
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
