# Generated by Django 3.0.8 on 2020-09-02 21:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200711_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Lugares',
            },
        ),
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('simbolo', models.CharField(max_length=15)),
                ('unidad_medida', models.CharField(max_length=10)),
                ('id_datos_generales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DatosGenerales')),
            ],
            options={
                'verbose_name': 'Parámetro',
                'verbose_name_plural': 'Parámetros',
                'ordering': ('nombre',),
            },
        ),
    ]
