# Generated by Django 3.0.8 on 2020-09-03 06:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200903_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='monitoreo',
            field=models.IntegerField(choices=[(4, 'Calidad de agua'), (5, 'Biomasa')]),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='pais',
            field=models.IntegerField(choices=[(2, 'Bolivia'), (3, 'Peru')]),
        ),
        migrations.CreateModel(
            name='Limites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLASE_A', models.FloatField(validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(58)])),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Parametros')),
            ],
            options={
                'verbose_name': 'Límites',
                'verbose_name_plural': 'Límites',
                'ordering': ('nombre',),
            },
        ),
    ]
