# Generated by Django 3.0.8 on 2020-09-06 05:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200903_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'Visor',
                'verbose_name_plural': 'Visor',
            },
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
        migrations.AlterModelOptions(
            name='limites',
            options={'verbose_name': 'Límites', 'verbose_name_plural': 'Límites'},
        ),
        migrations.RemoveField(
            model_name='limites',
            name='CLASE_A',
        ),
    ]
