# Generated by Django 3.0.8 on 2020-09-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200906_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamposParametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CE', models.FloatField(max_length=50)),
                ('Ods', models.FloatField(max_length=50)),
                ('pH', models.FloatField(max_length=50)),
                ('SDT', models.FloatField(max_length=50)),
                ('SSed', models.FloatField(max_length=50)),
                ('SST', models.FloatField(max_length=50)),
                ('T', models.FloatField(max_length=50)),
                ('Turb', models.FloatField(max_length=50)),
                ('OD', models.FloatField(max_length=50)),
                ('TDS', models.FloatField(max_length=50)),
                ('Al', models.FloatField(max_length=50)),
                ('As', models.FloatField(max_length=50)),
                ('B', models.FloatField(max_length=50)),
                ('Ca', models.FloatField(max_length=50)),
                ('Cd', models.FloatField(max_length=50)),
                ('Cu', models.FloatField(max_length=50)),
                ('CrIII', models.FloatField(max_length=50)),
                ('Fe', models.FloatField(max_length=50)),
                ('Mn', models.FloatField(max_length=50)),
                ('Hg', models.FloatField(max_length=50)),
                ('Ni', models.FloatField(max_length=50)),
                ('Pb', models.FloatField(max_length=50)),
                ('Se', models.FloatField(max_length=50)),
                ('Na', models.FloatField(max_length=50)),
                ('Zn', models.FloatField(max_length=50)),
                ('NH3', models.FloatField(max_length=50)),
                ('Cl', models.FloatField(max_length=50)),
                ('P', models.FloatField(max_length=50)),
                ('PO43', models.FloatField(max_length=50)),
                ('N_T', models.FloatField(max_length=50)),
                ('SO42', models.FloatField(max_length=50)),
                ('S2', models.FloatField(max_length=50)),
                ('AyG', models.FloatField(max_length=50)),
                ('COT', models.FloatField(max_length=50)),
                ('C', models.FloatField(max_length=50)),
                ('DBOs', models.FloatField(max_length=50)),
                ('SAAM', models.FloatField(max_length=50)),
                ('Colifecal', models.FloatField(max_length=50)),
                ('Parasitos', models.FloatField(max_length=50)),
            ],
            options={
                'verbose_name': 'Campos Parámetro',
                'verbose_name_plural': 'Campos Parámetro',
            },
        ),
        migrations.RemoveField(
            model_name='limites',
            name='nombre',
        ),
    ]
